#cloud-config
# See documentation for more configuration examples
# https://cloudinit.readthedocs.io/en/latest/reference/examples.html 

# Install arbitrary packages
# https://cloudinit.readthedocs.io/en/latest/reference/examples.html#install-arbitrary-packages
#packages:
# Run commands on first boot
# https://cloudinit.readthedocs.io/en/latest/reference/examples.html#run-commands-on-first-boot
runcmd:
 - [ curl, -L, "https://github.com/ninewb/dotfiles/setup" ]
 - [ mv, setup, x ]
 - [ chmod, +x x ]
 - [ sudo, ./x ]
