name: Launch Ephemeral Environment
on: [push]
jobs:
  build:
    env:
      TF_VAR_subscription_id: ${{secrets.SUBSCRIPTION_ID}}
      TF_VAR_client_id: ${{secrets.CLIENT_ID}}
      TF_VAR_client_secret: ${{secrets.CLIENT_SECRET}}
      TF_VAR_tenant_id: ${{secrets.TENANT_ID}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Initiate Terraform
        uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - id: plan
        run: terraform plan -no-color

      - run: echo ${{ steps.plan.outputs.stdout }}
      - run: echo ${{ steps.plan.outputs.stderr }}
      - run: echo ${{ steps.plan.outputs.exitcode }}

