name: Launch Ephemeral Environment
on: [push]
jobs:
  build:
    env:
      TF_VAR_tailscale_auth_key: ${{ secrets.TAILSCALE_OAUTH }}
      TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.TENANT_ID }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Update Variables
        run: |
          sudo apt-get install -qq -o=Dpkg::Use-Pty=0 moreutils -y
          echo ${{ vars.VM_CIDRS }}
          
          jq -r --argjson cidr ${{ vars.VM_CIDRS }} '.public_access_cidrs = $cidr' ${{ github.workspace }}/terraform.tfvars.json | sponge ${{ github.workspace }}/terraform.tfvars.
          cat ${{ github.workspace }}/terraform.tfvars.json

      - name: Setup Terraform   
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Initiate terraform
        uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - id: plan
        run: terraform plan -no-color
      - id: apply
        run: terraform apply --auto-approve

      - name: Grab Outputs
        run: |
          output=$(terraform output viya_instance_ip_addr)
          echo $output

      - name: Destroy Environment
        uses: hashicorp/setup-terraform@v3
      - run: terraform destroy --auto-approve
